### ISSUE TITLE
want sql-database table creation code file

### ISSUE THREAD

**Issue by Rahufkhan99** [adarshsuresh07/FeePayment#10]
can you please give me the sql-database-table creation code file so that i can crate tables in mysql database

**Comment by adarshsuresh12** [comment]
It's been 5 years since we done this project. So it might not be possible to give you the creation code now. You can refer the ER diagram and create a db if that helps.

**Comment by adarshsuresh07** [comment]
It's been 5 years since we did this project. So we might not be able to help you with the db creation code file. Please refer to ER diagram and if it helps, try creating db tables with that.
